### ISSUE TITLE
Create a Lambda Function

### ISSUE THREAD

**Issue by RosemaryOjwang** [RosemaryOjwang/Cloud-Resume-API#4]
### Task
- [ ] Create a Lambda Function.
- [ ] Create an IAM Role and assign it to the Lambda Function.
- [ ] Create a function URL.
- [ ] Build a REST API Gateway.
- [ ] Test the Lambda Function.
### Description
-  Define a Lambda function that retrieves the JSON resume data from DynamoDB.
 - Create an IAM role with necessary permissions to access DynamoDB.
 - Attach the IAM role to the Lambda function.
 - Build a REST API gateway.
 - Add the REST API gateway as a trigger event to the Lambda function.
 - Test the Lambda function.
